run:
  dataset: msra
  # dataset: weibo
  model: bert_wwm
  # model: bert_base

datasets:
  msra:
    dataset_path: "/home/sulin/Bert_NER/data/"
    dataset_name: "msra/"
    data_name: ".txt"
    class_num: 7
    tag_file: "/home/sulin/Bert_NER/data/msra/label.txt"

  weibo:
    dataset_path: "/home/sulin/Bert_NER/data/"
    dataset_name: "weibo/"
    data_name: ".txt"
    class_num: 17
    tag_file: "/home/sulin/Bert_NER/data/weibo/label.txt"

models:
  bert_wwm:
    bert_path: "/home/sulin/Bert_NER/pre_model/chinese-bert-wwm"
    hidden_size: 768

  bert_base:
    bert_path: "/home/sulin/Bert_NER/pre_model/bert-base-chinese"
    hidden_size: 768

train:
  epochs: 20
  batch_size: 64
  learning_rate: !!float 4e-5
  max_length: 128
  dropout: 0.1
