run:
  dataset: msra
  # dataset: weibo
  # model: bert_wwm
  model: bert_base

datasets:
  msra:
    dataset_path: "data/"
    dataset_name: "msra/"
    data_name: ".txt"
    class_num: 7
    tag_file: "data/msra/label.txt"

  weibo:
    dataset_path: "data/"
    dataset_name: "weibo/"
    data_name: ".txt"
    class_num: 17
    tag_file: "data/weibo/label.txt"

models:
  bert_wwm:
    bert_path: "pre_model/chinese-bert-wwm"
    hidden_size: 768

  bert_base:
    bert_path: "pre_model/bert-base-chinese"
    hidden_size: 768

train:
  weibo:
    epochs: 20
    batch_size: 32
    learning_rate: !!float 4e-5
    max_length: 128
    dropout: 0.1
  msra:
    epochs: 10
    batch_size: 256
    learning_rate: !!float 2e-4
    max_length: 128
    dropout: 0.1