run:
  # dataset: msra
  dataset: weibo
  model: bert_wwm
  # model: bert_base

datasets:
  msra:
    dataset_path: "/home/sulin/code/data/"
    dataset_name: "msra/"
    data_name: ".txt"
    class_num: 7
    tag_file: "/home/sulin/code/data/msra/class.txt"

  weibo:
    dataset_path: "/home/sulin/code/data/"
    dataset_name: "weibo/"
    data_name: ".txt"
    class_num: 17
    tag_file: "/home/sulin/code/data/weibo/class.txt"

models:
  bert_wwm:
    bert_path: "/home/sulin/code/pre_model/chinese-bert-wwm"
    hidden_size: 768

  bert_base:
    bert_path: "/home/sulin/code/pre_model/bert-base-chinese"
    hidden_size: 768

train:
  epochs: 3
  batch_size: 16
  learning_rate: !!float 2e-5
  max_length: 128
  dropout: 0.1
